### ISSUE TITLE
VPXTOOL panics when using assemble option

### ISSUE THREAD

**Issue by SandraZee** [francisdb/vpxtool#206]
When I try to use vpxtool to create a .vpx file from a disassembled directory, the program panics.  I may be using the program options incorrectly, if so, please correct me.
C:\Visual Pinball\Tables>set RUST_BACKTRACE=full

C:\Visual Pinball\Tables>vpxtool assemble FearAndLoathing
thread 'main' panicked at src/lib.rs:533:14:
internal error: entered unreachable code
stack backtrace:
   0:     0x7ff7e4eea623 - <unknown>
   1:     0x7ff7e4f0c9cd - <unknown>
   2:     0x7ff7e4ee59e1 - <unknown>
   3:     0x7ff7e4eea42a - <unknown>
   4:     0x7ff7e4eec979 - <unknown>
   5:     0x7ff7e4eec63b - <unknown>
   6:     0x7ff7e4eece64 - <unknown>
   7:     0x7ff7e4eeccfb - <unknown>
   8:     0x7ff7e4eeaf19 - <unknown>
   9:     0x7ff7e4eeca44 - <unknown>
  10:     0x7ff7e4f229b7 - <unknown>
  11:     0x7ff7e4f22a72 - <unknown>
  12:     0x7ff7e4bb0a44 - <unknown>
  13:     0x7ff7e4ba85c8 - <unknown>
  14:     0x7ff7e4bcc95a - <unknown>
  15:     0x7ff7e4ba1006 - <unknown>
  16:     0x7ff7e4edf9e8 - <unknown>
  17:     0x7ff7e4ba1038 - <unknown>
  18:     0x7ff7e4f13184 - <unknown>
  19:     0x7ffa727f257d - BaseThreadInitThunk
  20:     0x7ffa72c4aa58 - RtlUserThreadStart
Thank you!  
-Sandy

**Comment by francisdb** [comment]
Hi Sandy,
I fear that that part of vpxtool is not ready yet. What is your use case?

**Comment by SandraZee** [comment]
Hi Francis,
I am working with other virtual pinball enthusiasts and are modding a table.  I was hoping to use vpxtool as an instrument that would break out and reassemble the assets of a .vpx file so they can be controlled through github.  The program does the breaking out very well.  The target directory holds all the assets we want to modify.  It would make it very simple if we could reverse the process to create the updated .vpx file.

**Comment by francisdb** [comment]
Exactly that use case is planned. Still need to work out 3d and texture formats. Maybe the fact that more ppl are looking for this will make me actually finish this :-)

**Comment by SandraZee** [comment]
It would help a lot.  You certainly have my vote!

**Comment by francisdb** [comment]
Just letting you know that this work is progressing at https://github.com/francisdb/vpin/pull/21
I can already expand and assemble but need to implement/revise some more file formats before I can bring this to vpxtool

<img width="610" alt="image" src="https://github.com/francisdb/vpxtool/assets/161305/60c0ec88-2056-4439-8d81-207f7fab8ddb">

**Comment by francisdb** [comment]
Some example of current progress: https://github.com/francisdb/volkan-vpx-expanded

**Comment by SandraZee** [comment]
That is quite good progress.  That particular table is intricate and finding all the moving parts is very good.  Are you now able to identify all the file types used in a .vpx file?  I believe you mentioned that identifying all the file types has been an issue for the assembly portion of the program.

**Comment by francisdb** [comment]
All data from the vpx is in that repo. I can reassemble it fully from those files.

But the next part is creating the files for the primitives (3d objects) instead of those .bin files.

Then I'll integrate everything in vpxtool.

**Comment by francisdb** [comment]
Hmm, looks like there might be some remaining issues as vpinball hangs on some re-assembled tables. Looking into it.

**Comment by francisdb** [comment]
Fixed in https://github.com/francisdb/vpxtool/releases/tag/v0.10.1

**Comment by SandraZee** [comment]
I'm using 11.7, and VPXTOOL does not extract/assemble a working table. You said it works in standalone mode, but I may not understand what standalone means in this context. I'm using Windows 11 and, VPX 10.7.3 and 10.8 RC 2.  Any help would be appreciated.  Thanks!

**Comment by francisdb** [comment]
See #276 I submitted a fix but need to wait for it to be accepted/released.

**Comment by SandraZee** [comment]
I understand.  Thank you for your efforts!  It is appreciated!

**Comment by francisdb** [comment]
Fix for assembled vpx files reading on windows released https://github.com/francisdb/vpxtool/releases/tag/v0.11.8
