### ISSUE TITLE
Policy on downstream use?

### ISSUE THREAD

**Issue by rh6423** [francisdb/vpxtool#244]
I'm developing a cross-platform launcher and table manager GUI app, and I'm interested in bundling vpxtool with my app. There are a couple of functions I'd rather reuse from vpxtool than write, and users could also run vpxtool directly as needed. My repo is https://github.com/rh6423/flipper-fiend/tree/main (it's a work in progress, your policy is kind of relevant to what I work on next). If bundling is something you'd rather I not do, I'll respect your wishes.

**Comment by francisdb** [comment]
I'm all ok with that. No problem. But might be better to have your frontend download the latest release from GitHub instead of bundling? Will sure have a look at what you are building! Let me know if you need any extra vpxtool features.
