### ISSUE TITLE
assemble command produces vpx file with errors

### ISSUE THREAD

**Issue by mpcarr** [francisdb/vpxtool#276]
Using the extract command and then assemble produces a vpx file with missing layers and warnings.

see: https://github.com/mpcarr/aztec-quest

![image](https://github.com/francisdb/vpxtool/assets/6593426/090cd9ee-a5f6-44f9-87f7-9c4131c13c00)

![image](https://github.com/francisdb/vpxtool/assets/6593426/9da2723c-1ddb-4d4a-97f4-33dd55730b4b)

Before extract and assemble.

![image](https://github.com/francisdb/vpxtool/assets/6593426/20f04f10-e389-4967-b6b1-d3b9c76eb41d)

Re assembled file.

![image](https://github.com/francisdb/vpxtool/assets/6593426/73f3bee1-0b18-44d2-9282-7c684469e953)

**Comment by francisdb** [comment]
That's pretty serious, I have mainly been testing with vpinball standalone, maybe some more checks are applied when editing.

Looking into it tomorrow. Thanks for testing!

**Comment by mpcarr** [comment]
I've just tested to confirm the table works on standalone prior to extracting and re-assembling.
I then used the extract and assemle commands on linux and tried to play the assebled file on standalone again and it gets stuck at LoadData.

**Comment by mpcarr** [comment]
> I hope it's fixed in https://github.com/francisdb/vpxtool/releases/tag/v0.11.7 The assembled table now loads correctly in standalone. (you will have to re-extract first as some fields were changed)
> 
> Please let me know if the issue is fixed or not.

fixed in standalone player but windows vpx still gives above warnings and mising layers

**Comment by francisdb** [comment]
Underlying issue reported at https://github.com/mdsteele/rust-cfb/issues/52

**Comment by francisdb** [comment]
I hope this is finally fixed in [0.11.8](https://github.com/francisdb/vpxtool/releases/tag/v0.11.8)

**Comment by francisdb** [comment]
@SandraZee are you on the "Virtual Pinball Chat" discord?

**Comment by SandraZee** [comment]
Yes I am, though I am not as active as I have wanted.  I spend a lot of time in other developments.

**Comment by SandraZee** [comment]
I am DrSandraNo on VP Chat.
