### ISSUE TITLE
Not exporting bmp correctly ?

### ISSUE THREAD

**Issue by sverrewl** [francisdb/vpxtool#301]
Cool tool - has its use cases for sure.

I started looking into improving Algar with lightmapper. 

Task, convert BMP to WEBP. 

After extract of the table, neither PS6 or latest Gimp would recognize the file. 
Manually exporting it via VPX worked.

**Comment by francisdb** [comment]
Thanks for reporting this!

**Comment by francisdb** [comment]
This one?
https://www.vpforums.org/index.php?app=downloads&showfile=13520

**Comment by sverrewl** [comment]
https://www.dropbox.com/scl/fi/qusdb9jzib6v7foyloned/Algar-Williams-1980-1.37_VPX8_Lampz.vpx?rlkey=oxeuonz0hx9ixt78rzt9prt2j&st=79rs576t&dl=1

If I remember correctly, I had a 1.34 out on vpinball. Could not find it on VPU where I would have uploaded it. I've fiddled with this on and off experimenting with techniques more than anything. Seems to still be a valid vpx, but, as I said, failed exporting. Never tried the vpforum one. Was a joint effort originally and I didn't want to upload to vpforums. Still don't want to.

**Comment by francisdb** [comment]
I see not `.bmp` files when I extract your file?

**Comment by francisdb** [comment]
Looks like I'm indeed writing just the byte buffer instead of a proper bmp. Working on a fix.
