### ISSUE TITLE
Killed: 9 (MacOS, Monterey)

### ISSUE THREAD

**Issue by EngineersNeedArt** [francisdb/vpxtool#304]
Hi, Francis — 

Trying to help an artist friend in Austria (I believe) use `vpxtool`. He's new to C/L tools in general.

He's hitting `Killed: 9` when he tries to use `vpxtool`. I think this is even with a simple `--help` option. He is on a nice MacStudio machine I believe so I pointed him to your `vpxtool-macOS-aarch64-v0.13.1.tar.gz` version.

Any ideas?

**Comment by francisdb** [comment]
Did he follow the instructions on getting the file out of quarantine?

https://github.com/francisdb/vpxtool?tab=readme-ov-file#macos

**Comment by EngineersNeedArt** [comment]
Almost certainly what the problem is. Thanks. I am an idiot — I did that for myself but then forget it when I "help" someone else to install.

**Comment by francisdb** [comment]
Wouldn't be so sure as I could not reproduce that error. Updated my previous reply with some more ways to debug this.
