### ISSUE TITLE
Great tool - would you consider adding a default_output_dir ... or something in that direction for extractvbs ?

### ISSUE THREAD

**Issue by sverrewl** [francisdb/vpxtool#410]
Upgraded my cab, and loading vpx files, extracting vbs files is so much slower than it used to be on Win7. This tool has always been blazing fast and I've used it several times outside of the windows platform. Really a cool tool.

I can live with the slow wrapper that I'm using, but, if only we could have a setting to tell what folder the extracted vbs would go to, it would be my new tool for sure.

**Comment by francisdb** [comment]
@sverrewl happy to hear you enjoy using vpxtool

Could you explain your use case? I'm wondering why you would want to extract all vbs files to a single folder as they only are picked up when placed next to the table.

**Comment by sverrewl** [comment]
It is because I run through almost every script there is, checking for things that I want to change. Like kickers not having randomness applied to them. Not using vpminit, not having ssf etc. etc. Far from every script will be edited, but, it can be very convenient having a huge archive of scripts laying around. Except for gaming, linux is my main OS, so, I'm quite used to processing text files using perl and vim. Today the process is like ... make a hash map of scripts I've got. Run that against the new table names. If I find a new one it gets extracted to c:\temp where I later move it to my server for further processing. Cleaning + Git etc.

I'm sure you are aware of https://github.com/sverrewl/vpxtable_scripts - that hasn't been updated, except for when there is a table where there is a solution maybe hidden in the forum thread, but, no update. Things like that. My archive is much larger though and contains old folder, more like a deep archive. All these scripts doesn't take up much hard-drive space, so, why not keep them.

A config line or maybe better. A output parameter is what I really would like to see implemented.

**Comment by francisdb** [comment]
Ha yes, I saw that repo. Thank you for feeding the AI bots so they can help writing table scripts :+1: 

This would be most natural I think.

```
vpxtool extractvbs foo.vpx /tmp/test/foo.vbs
```

Or would you prefer below where you don't have to repeat the filename?

```
vpxtool extractvbs foo.vpx --dir /tmp/test
```

Could of course implement both and fail if `--dir` is used in combination with the first case.

**Comment by francisdb** [comment]
By the way I use your repo to test my vbscript parser: https://github.com/francisdb/vbscript.rs/blob/main/testscripts/populate.sh

**Comment by francisdb** [comment]
I hope 0.18.0 has what you need.

**Comment by sverrewl** [comment]
Busy with other tasks, but, now just implemented it and as expected -blazing fast. Thanks again <3
